pipeline {
    agent any
    tools {
        // Install the Maven version configured as "M3" and add it to the path.
        maven "M3"
    }
	stages {
        stage('Preparing') {
            steps {
                // Get some code from a GitHub repository
                git 'http://chungsju:king2331@172.31.1.194:580/chungsju/bwcicd.git'
            }
        }
        stage('Test') {
            steps {
                echo "Skip Test"
            }
        }
        stage('Package') {
            steps {
                 sh "mvn clean package -f cicd3.application.parent/pom.xml"
            }
        }
        stage('Deploy') {
            steps {
                sh "mvn install -f cicd3.application.parent/pom.xml"
            }
        }
    }
}
